import React from "react";
import {
  FaTwitter,
  FaFacebookF,
  FaWhatsapp,
  FaEnvelope,
  FaReddit,
} from "react-icons/fa";
import ShareBtn from "./ShareBtn";
import ShareBtnfooter from "@/button/ShareBtnfooter";
import NeverSearch from "./NeverSearch";

function PrivacyPage() {
  return (
    <div className="max-w-4xl mx-auto p-4 md:p-6 text-[#0B3C3A]">
      {/* Header */}
      <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-center mb-4 md:mb-6">
        Privacy Policy
      </h1>

      {/* Content */}
      <p className="text-sm sm:text-base p-2 sm:p-4">
        This privacy policy sets out how matchedbettingblog.com uses and
        protects any information that you provide when using this website.
      </p>

      <p className="text-sm sm:text-base mt-3 sm:mt-4">
        This privacy policy sets out how matchedbettingblog.com uses and
        protects any information that you provide when using this website.
      </p>
      <p className="text-sm sm:text-base mt-3 sm:mt-4">
        Matchedbettingblog.com is committed to ensuring that your privacy is
        protected. Should I ask you to provide certain information by which you
        can be identified when using this website; you can be assured that it
        will only be used in accordance with this privacy policy
      </p>
      <p className="text-sm sm:text-base mt-3 sm:mt-4">
        Matchedbettingblog.com may update this policy in the future. You should
        therefore check this page from time to time to ensure that you are happy
        with any changes.
      </p>

      <div className="flex flex-col gap-2 sm:gap-3 items-start mt-6 sm:mt-8">
        <h3 className="text-xl sm:text-2xl md:text-3xl font-bold text-center mb-4 sm:mb-6">
          What information is collected?
        </h3>
        <p className="text-sm sm:text-base mt-1">
          If you have an account and you log in to this site, a temporary cookie
          will be set to determine if your browser accepts cookies. This cookie
          contains no personal data and is discarded when you close your
          browser.
        </p>
        <p className="text-sm sm:text-base mt-3 sm:mt-4">
          When you log in, several cookies will also be set up to save your
          login information and your screen display choices. Login cookies last
          for two days, and screen options cookies last for a year. If you
          select “Remember Me”, your login will persist for two weeks. If you
          log out of your account, the login cookies will be removed.
        </p>
      </div>

      <div className="flex flex-col gap-2 sm:gap-3 items-start mt-6 sm:mt-8">
        <h3 className="text-xl sm:text-2xl md:text-3xl font-bold text-center mb-4 sm:mb-6">
          Embedded content from other websites
        </h3>
        <p className="text-sm sm:text-base mt-1">
          Articles on this site may include embedded content (e.g. videos,
          images, articles, etc.). Embedded content from other websites behaves
          in the exact same way as if the visitor has visited the other website.
        </p>
        <p className="text-sm sm:text-base mt-3 sm:mt-4">
          These websites may collect data about you, use cookies, embed
          additional third-party tracking, and monitor your interaction with
          that embedded content, including tracing your interaction with the
          embedded content if you have an account and are logged in to that
          website.
        </p>
      </div>

      <div className="flex flex-col gap-2 sm:gap-3 items-start mt-6 sm:mt-8">
        <h3 className="text-xl sm:text-2xl md:text-3xl font-bold text-center mb-4 sm:mb-6">
          Analytics
        </h3>
        <p className="text-sm sm:text-base mt-1">
          Our website uses Google Analytics, a web analytics service provided by
          Google. The information generated by the cookie about your use of this
          website (including your IP address) will be transmitted to and stored
          by Google. Google will use this information for the purpose of
          evaluating your use of this website, compiling reports on website
          activity for website operators and providing other services relating
          to website activity and internet usage.
        </p>
        <p className="text-sm sm:text-base mt-3 sm:mt-4">
          Google may also transfer this information to third parties where
          required to do so by law, or where such third parties process the
          information on Google’s behalf. Google will not associate your IP
          address with any other data held by Google.
        </p>
      </div>

      <div className="flex flex-col gap-2 sm:gap-3 items-start mt-6 sm:mt-8">
        <h3 className="text-xl sm:text-2xl md:text-3xl font-bold text-center mb-4 sm:mb-6">
          What I do with the information I gather
        </h3>
        <p className="text-sm sm:text-base mt-1">
          Information is collected to understand your needs and provide you with
          a better service. The information generated by the cookie about your
          use of this website (including your IP address) will be transmitted to
          and stored by Google. Google will use this information for the purpose
          of evaluating your use of this website, compiling reports on website
          activity for website operators and providing other services relating
          to website activity and internet usage.
        </p>
        <p className="text-sm sm:text-base mt-3 sm:mt-4">
          Google may also transfer this information to third parties where
          required to do so by law, or where such third parties process the
          information on Google’s behalf. Google will not associate your IP
          address with any other data held by Google.
        </p>
      </div>

      <div className="flex flex-col gap-2 sm:gap-3 items-start mt-6 sm:mt-8">
        <h3 className="text-xl sm:text-2xl md:text-3xl font-bold text-center mb-4 sm:mb-6">
          Security
        </h3>
        <p className="text-sm sm:text-base mt-1">
          I am committed to ensuring that your information is secure. In order
          to prevent unauthorised access or disclosure, I have put in place
          suitable electronic procedures to safeguard and secure the information
          I collect online.
        </p>
      </div>

      <div className="flex flex-col gap-2 sm:gap-3 items-start mt-6 sm:mt-8">
        <h3 className="text-xl sm:text-2xl md:text-3xl font-bold text-center mb-4 sm:mb-6">
          How I use cookies
        </h3>
        <p className="text-sm sm:text-base mt-1">
          Cookies are text files stored on your computer, and accessible only to
          the websites which create them.
        </p>
        <p className="text-sm sm:text-base mt-3 sm:mt-4">
          This website may from time to time use cookies and log files for
          statistical analysis, to understand user behaviour, to maintain the
          site, to tailor the information presented to a user based on their
          preferences, and to improve overall user experience.
        </p>

        <p className="text-sm sm:text-base mt-3 sm:mt-4">
          You can choose to accept or decline cookies. Most web browsers
          automatically accept cookies, but you can modify your browser setting
          to decline cookies if you prefer. This may prevent you from taking
          full advantage of the website
        </p>
      </div>

      {/* Social Share Buttons */}

      {/* Subscribe Section */}
      <div className="p-4 sm:p-6 mt-8 sm:mt-10 rounded-md text-center">
        <h2 className="text-lg sm:text-xl font-bold">Never miss an offer!</h2>
        <div className="flex flex-col">
          <p className="text-sm sm:text-base">
            I may periodically send promotional emails about special offers or
            other information which I think you may find interesting. These
            emails will only be sent to users who have provided their email
            address for that specific purpose.
          </p>
          <p className="text-sm sm:text-base">
            From time to time, I may also contact you by email for market
            research purposes. Any information gathered would be used to improve
            the website.
          </p>
        </div>
        <div className="flex mt-4 justify-center">
          <ShareBtnfooter />
        </div>
      </div>
    </div>
  );
}

export default PrivacyPage;
