import { Inter } from "next/font/google";
import "./globals.css";
import LayoutPage from "@/layout/LayoutPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Matched Betting Blog 2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutPage>{children}</LayoutPage>
      </body>
    </html>
  );
}
